### ISSUE TITLE
not working with rails 5

### ISSUE THREAD

**Issue by nelsongc** [adamcooke/send_file_with_range#1]
in rails 5.1.1 not working

gems/send_file_with_range-1.0.0/lib/send_file_with_range/controller_extension.rb:5:in `included': undefined method `alias_method_chain' for ActionController::DataStreaming:Module (NoMethodError)

**Comment by tom-sherman** [comment]
@metalels has fixed this in his fork, although for some reason he hasn't submitted a PR.

As a temporary fix you can add this to your Gemfile

```
gem 'send_file_with_range', git: 'https://github.com/metalels/send_file_with_range.git', branch: 'rails51'
```
I have it working on rails 5.1.3 & ruby 2.4.1

---

**Edit:** I have submitted a PR using matalels code (#2)
